# Generated by Django 4.2 on 2023-04-21 01:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistroCurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distroID', models.IntegerField()),
                ('socketNum', models.IntegerField()),
                ('currentValue', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distro_location', models.CharField(max_length=200)),
                ('socket_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Traders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TraderToDistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_number', models.IntegerField(default=0)),
                ('start_time', models.DateField(default=django.utils.timezone.now)),
                ('distro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rad.distros')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rad.traders')),
            ],
        ),
    ]
